name: Build and Test App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Debug Secrets
        run: echo "DOCKER_USER=${{ secrets.DOCKER_USER }}" && echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Tag
        id: tag
        run: echo "TAG=mdo-posts-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Print Docker Tag
        run: echo "${{ env.TAG }}"

      - name: Build the Docker image
        id: build
        run: docker build . --file Dockerfile --tag ${{ env.TAG }}

      - name: Push the Docker image
        id: push
        run: docker push ${{ env.TAG }}
